general.import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "Mononoki Nerd Font Mono"

size = 13
